//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dlg.rc
//
#define IDSYSPOPUP_CLOSE                1
#define VS_VERSION_INFO                 1
#define IDSYSPOPUP_FIRST                2
#define DLG_TRAY_OPTIONS                6
#define DLG_TRAY_VIEW_OPTIONS           6
#define DLG_NOTIFY                      7
#define DLG_STARTMENU_CONFIG            9
#define DLG_EXTRA_OPTIONS               10
#define DLG_PROGRAMFILECONFLICT         20
#define ICO_FIRST                       100
#define ICO_MYCOMPUTER                  100
#define ICO_TREEUP_EXPLORER             101
#define ICO_OLD_PRINTER                 102
#define ICO_DESKTOP                     103
#define ICO_OLD_PRINTER_ERROR           104
#define ICO_STARTMENU                   107
#define ICO_DOCMENU                     108
#define ICO_OLD_INFO                    109
#define ICO_OLD_WARNING                 110
#define ICO_OLD_ERROR                   111
#define IDB_START                       143
#define IDB_TAAUTOHIDE                  145
#define IDB_TAQLLOCKGROUP               146
#define IDB_TAQLNOLOCKGROUP             147
#define IDB_TAQLLOCKNOGROUP             148
#define IDB_TAQLNOLOCKNOGROUP           149
#define IDB_TALOCKGROUP                 150
#define IDB_TANOLOCKGROUP               151
#define IDB_TALOCKNOGROUP               152
#define IDB_TANOLOCKNOGROUP             153
#define IDB_SERVERSTARTBKG              158
#define IDB_PROFESSIONALSTARTBKG        167
#define IDB_STARTPREVIEWNEW             170
#define IDB_STARTPREVIEWCLASSIC         171
#define IDB_TRAYCHEVRONHORIZ            172
#define IDB_TRAYCHEVRONHORIZOPEN        173
#define IDB_TRAYCHEVRONVERT             174
#define IDB_TRAYCHEVRONVERTOPEN         175
#define IDB_STARTCLASSIC                176
#define IDB_START16                     178
#define IDB_START16MASK                 179
#define IDB_NACLOCKCLEAN                180
#define IDB_NANOCLOCKCLEAN              181
#define IDB_NACLOCKNOCLEAN              182
#define IDB_NANOCLOCKNOCLEAN            183
#define ICO_SHOWALL                     200
#define MENU_CABINET                    200
#define ICO_HIDEHIDDEN                  201
#define ICO_HIDESYSTEM                  202
#define ICO_MULTWIN                     203
#define MENU_TRAY                       203
#define MENU_START                      204
#define DLG_START                       205
#define ICO_OLD_MYCOMPUTER              205
#define MENU_TRAYCONTEXT                205
#define MENU_COMBINEDTASKS              209
#define MENU_GROUPCONTEXT               210
#define MENU_STARTPANECONTEXT           211
#define ICO_SHOWDEMOTED                 250
#define ICO_HIDEDEMOTED                 251
#define ACCEL_TRAY                      251
#define ICO_TRAYPROP_PLACEHOLDER        252
#define ICO_INTERNETBROWSER             253
#define ICO_INTERNETMAIL                254
#define ICO_MEDIAPLAYER                 255
#define ICO_WORDMAIL                    256
#define ICO_CLASSICSM                   257
#define ICO_START2K                     258
#define IDC_GROUPBOX                    300
#define IDC_GROUPBOX_2                  301
#define IDC_GROUPBOX_3                  302
#define IDC_CLOCK                       303
#define IDC_START                       304
#define IDC_KBSTART                     305
#define IDC_ASYNCSTART                  306
#define IDC_RAISEDESKTOP                307
#define IDM_RESTORE                     310
#define IDM_MINIMIZE                    311
#define IDM_MAXIMIZE                    312
#define IDM_TRAYCONTEXTFIRST            400
#define IDM_FILERUN                     401
#define IDM_LOGOFF                      402
#define IDM_CASCADE                     403
#define IDM_HORIZTILE                   404
#define IDM_VERTTILE                    405
#define IDM_DESKTOPARRANGEGRID          406
#define IDM_TOGGLEDESKTOP               407
#define IDM_SETTIME                     408
#define IDM_SUSPEND                     409
#define IDM_EJECTPC                     410
#define IDM_SETTINGSASSIST              411
#define IDM_TASKLIST                    412
#define IDM_TRAYPROPERTIES              413
#define IDM_UPDATEWIZARD                414
#define IDM_MINIMIZEALL                 415
#define IDM_UPDATE_SEP                  415
#define IDM_UNDO                        416
#define IDM_RETURN                      417
#define IDM_PRINTNOTIFY_FOLDER          418
#define IDM_MINIMIZEALLHOTKEY           419
#define IDM_SHOWTASKMAN                 420
#define IDM_NOTIFYCUST                  421
#define IDM_UNGROUP                     422
#define IDM_SIZEUP                      427
#define IDM_SIZEDOWN                    428
#define IDM_SEP2                        450
#define IDM_RECENT                      501
#define IDM_FIND                        502
#define IDM_HELPSEARCH                  503
#define IDM_PROGRAMS                    504
#define IDM_CONTROLS                    505
#define IDM_EXITWIN                     506
#define IDM_FAVORITES                   507
#define IDM_SETTINGS                    508
#define IDS_CABINET                     509
#define IDS_STARTMENU                   510
#define IDM_PRINTERS                    510
#define IDM_STARTMENU                   511
#define IDM_MYCOMPUTER                  512
#define IDS_WINDOWS                     513
#define IDM_PROGRAMSINIT                513
#define IDS_CLOSE                       514
#define IDM_RECENTINIT                  514
#define IDS_WINININORUN                 515
#define IDM_MYDOCUMENTS                 516
#define IDS_TASKBAR                     518
#define IDM_MENU_FIND                   520
#define TRAY_IDM_FINDFIRST              521
#define IDS_CONTENTSOF                  523
#define IDS_DESKTOP                     524
#define IDS_SUSPENDERROR1               525
#define IDS_SUSPENDERROR2               526
#define IDS_OUTOFMEM                    529
#define IDS_CANTFINDSPECIALDIR          530
#define IDS_NOTINITED                   531
#define IDS_STARTBUTTONTIP              533
#define IDS_UNDOTEMPLATE                534
#define IDS_CASCADE                     535
#define IDS_TILE                        536
#define IDS_MINIMIZEALL                 537
#define IDS_CLEANBOOTMSG                538
#define IDS_CLEANBOOTMSGRESTORE         539
#define IDS_HIDEDEMOTEDTIP              542
#define IDS_SHOWDEMOTEDTIP              543
#define IDS_BANNERFIRST                 544
#define TRAY_IDM_FINDLAST               550
#define IDM_DESKTOPHTML_CUSTOMIZE       552
#define IDM_DESKTOPHTML_UPDATE          553
#define IDM_CSC                         553
#define IDM_DESKTOPHTML_ONOFF           554
#define IDM_FOLDERPROPERTIES            555
#define IDM_ACTIVEDESKTOP_PROP          556
#define IDM_NETCONNECT                  557
#define IDS_BANNERLAST                  575
#define IDS_START                       578
#define IDS_EXCEPTIONMSG                579
#define IDS_RESTRICTIONSTITLE           580
#define IDS_RESTRICTIONS                581
#define IDS_BANGICONINFOTITLE           590
#define IDS_BANGICONINFOTIP1            591
#define IDS_TRAYNOTIFYTITLE             593
#define IDS_TASKBANDTITLE               594
#define IDS_STARTCLASSIC                595
#define IDS_OKTOKILLAPP1                603
#define IDS_OKTOKILLAPP2                604
#define IDC_NO_HELP_1                   650
#define IDC_NO_HELP_2                   651
#define IDC_NO_HELP_3                   652
#define IDC_NO_HELP_4                   653
#define MH_POPUPS                       700
#define IDC_ALWAYS                      700
#define IDC_NEVER                       701
#define IDS_DISPLAY_ERROR               701
#define IDS_DISPLAY_WARN                702
#define IDS_ALREADYAUTOHIDEBAR          705
#define IDS_TASKDROP_ERROR              711
#define IDS_COMMON                      716
#define IDS_BETAEXPIRED                 717
#define IDS_OPENCOMMON                  718
#define IDS_EXPLORECOMMON               719
#define IDS_STARTMENUPROP               720
#define IDS_RUNDLGTITLE                 722
#define IDS_LOGOFFNOUSER                730
#define IDS_TURNOFFCOMPUTER             731
#define IDS_HELP_CMD                    732
#define IDS_NOTITLE                     733
#define IDC_SHOWALL                     750
#define IDC_SHOWSYS                     751
#define IDC_SHOWSOME                    752
#define IDC_SHOWFULLPATH                753
#define IDC_HIDEEXTS                    754
#define IDC_SHOWDESCBAR                 755
#define IDC_SHOWCOMPCOLOR               756
#define IDS_STARTMENUBALLOON_TITLE      800
#define IDS_STARTMENUBALLOON_TIP        801
#define IDS_STARTMENUANDTASKBAR         810
#define IDS_FIXSCREENRES_TITLE          811
#define IDS_FIXSCREENRES_TEXT           812
#define IDS_OFFERTOUR_TITLE             821
#define IDS_OFFERTOUR_TEXT              822
#define IDS_HIDEDESKTOP                 850
#define IDS_BOGUSLABELS                 851
#define IDC_NOTIFY_OFF                  1000
#define IDS_NOTIFYNAME                  1000
#define IDC_NOTIFYMAN                   1000
#define IDB_RESTORE                     1001
#define IDS_BEHAVIOR                    1001
#define IDC_TOP                         1001
#define IDS_AUTOMATIC                   1002
#define IDC_BOTTOM                      1002
#define IDS_HIDDEN                      1003
#define IDC_LEFT                        1003
#define IDS_VISIBLE                     1004
#define IDS_NOTIFY_FIRST                IDS_AUTOMATIC 
#define IDS_NOTIFY_LAST                 (IDS_VISIBLE + 1)
#define IDC_RIGHT                       1004
#define IDC_NOTIFY_ITEMS                1005
#define IDC_COMBO_ACTION                1006
#define IDC_RENAME                      1006
#define IDC_CUSTOMIZE                   1007
#define IDC_MSG                         1007
#define IDC_EXTRAOPTWIN98               1008
#define DLG_PAGE_SMADVANCED             1036
#define IDC_TRAYOPTONTOP                1101
#define IDC_TRAYOPTAUTOHIDE             1102
#define IDC_TRAYOPTSHOWCLOCK            1103
#define IDC_GROUPITEMS                  1104
#define IDC_ENABLEMOVERESIZE            1105
#define IDC_STATIC_NOTIFY               1106
#define IDC_QUICKLAUNCH                 1107
#define IDC_TASKBARAPPEARANCE           1111
#define IDC_NOTIFYAPPEARANCE            1112
#define IDC_STARTMENUSETTINGS           1123
#define IDC_RESORT                      1124
#define IDC_KILLDOCUMENTS               1125
#define IDC_ADDSHORTCUT                 1126
#define IDC_DELSHORTCUT                 1127
#define IDC_EXPLOREMENUS                1128
#define IDC_OLDSTARTCUSTOMIZE           1130
#define IDC_NEWSTARTCUSTOMIZE           1131
#define IDC_PICTSMICONS                 1131
#define IDC_NEWSCHOOL                   1132
#define IDC_STARTMENUSETTINGSTEXT       1132
#define IDC_OLDSCHOOL                   1133
#define IDC_STARTMENUPREVIEW            1134
#define IDC_NEWSCHOOLDESCRIPTION        1135
#define DLG_PAGE_SMGENERAL              1135
#define IDC_SPCUST_ICONSMALL            1300
#define IDC_SPCUST_ICONLARGE            1301
#define IDC_SPCUST_LARGE                1302
#define IDC_SPCUST_SMALL                1303
#define IDC_SPCUST_MINPROGS             1304
#define IDC_SPCUST_MINPROGS_ARROW       1305
#define IDC_SPCUST_HOVEROPEN            1306
#define IDC_SPCUST_RECENT               1308
#define IDB_SPCUST_CLEARDOCS            1309
#define IDB_SPCUST_CLEARPROG            1310
#define IDS_SPCUST_TITLE                1311
#define IDC_SPCUST_RECENT_TEXT          1312
#define IDC_SPCUST_RECENT_GROUPBOX      1313
#define IDC_SPCUST_INTERNET             1320
#define IDC_SPCUST_INTERNETCB           1321
#define IDC_SPCUST_EMAIL                1322
#define IDC_SPCUST_EMAILCB              1323
#define IDC_SPCUST_NOTIFYNEW            1326
#define IDC_NOTIFY_TEXT                 1400
#define IDC_NOTIFY_TEXT2                1401
#define IDB_NOTIFY_RESTOREDEFAULTS      1402
#define IDS_NOTIFY_CURRENTITEMS         1403
#define IDS_NOTIFY_PASTITEMS            1404
#define IDC_PERSONALIZEDMENUS           1500
#define IDC_TRAYNOTIFY_CHEVRON          1502
#define IDS_MFU_PRO32ALL_00             2048
#define IDS_MFU_PRO32ALL_01             2049
#define IDS_MFU_PRO32ALL_02             2050
#define IDS_MFU_PRO32ALL_03             2051
#define IDS_MFU_PRO32ALL_04             2052
#define IDS_MFU_PRO32ALL_05             2053
#define IDS_MFU_PRO32ALL_06             2054
#define IDS_MFU_PRO32ALL_07             2055
#define IDS_MFU_PRO32ALL_08             2056
#define IDS_MFU_PRO32ALL_09             2057
#define IDS_MFU_PRO32ALL_10             2058
#define IDS_MFU_PRO32ALL_11             2059
#define IDS_MFU_PRO32ALL_12             2060
#define IDS_MFU_PRO32ALL_13             2061
#define IDS_MFU_PRO32ALL_14             2062
#define IDS_MFU_PRO32ALL_15             2063
#define IDS_MFU_PRO64ALL_00             2064
#define IDS_MFU_PRO64ALL_01             2065
#define IDS_MFU_PRO64ALL_02             2066
#define IDS_MFU_PRO64ALL_03             2067
#define IDS_MFU_PRO64ALL_04             2068
#define IDS_MFU_PRO64ALL_05             2069
#define IDS_MFU_PRO64ALL_06             2070
#define IDS_MFU_PRO64ALL_07             2071
#define IDS_MFU_PRO64ALL_08             2072
#define IDS_MFU_PRO64ALL_09             2073
#define IDS_MFU_PRO64ALL_10             2074
#define IDS_MFU_PRO64ALL_11             2075
#define IDS_MFU_PRO64ALL_12             2076
#define IDS_MFU_PRO64ALL_13             2077
#define IDS_MFU_PRO64ALL_14             2078
#define IDS_MFU_PRO64ALL_15             2079
#define IDS_MFU_SRV32ADM_00             2080
#define IDS_MFU_SRV32ADM_01             2081
#define IDS_MFU_SRV32ADM_02             2082
#define IDS_MFU_SRV32ADM_03             2083
#define IDS_MFU_SRV32ADM_04             2084
#define IDS_MFU_SRV32ADM_05             2085
#define IDS_MFU_SRV32ADM_06             2086
#define IDS_MFU_SRV32ADM_07             2087
#define IDS_MFU_SRV32ADM_08             2088
#define IDS_MFU_SRV32ADM_09             2089
#define IDS_MFU_SRV32ADM_10             2090
#define IDS_MFU_SRV32ADM_11             2091
#define IDS_MFU_SRV32ADM_12             2092
#define IDS_MFU_SRV32ADM_13             2093
#define IDS_MFU_SRV32ADM_14             2094
#define IDS_MFU_SRV32ADM_15             2095
#define IDS_MFU_SRV64ADM_00             2096
#define IDS_MFU_SRV64ADM_01             2097
#define IDS_MFU_SRV64ADM_02             2098
#define IDS_MFU_SRV64ADM_03             2099
#define IDS_MFU_SRV64ADM_04             2100
#define IDS_MFU_SRV64ADM_05             2101
#define IDS_MFU_SRV64ADM_06             2102
#define IDS_MFU_SRV64ADM_07             2103
#define IDS_MFU_SRV64ADM_08             2104
#define IDS_MFU_SRV64ADM_09             2105
#define IDS_MFU_SRV64ADM_10             2106
#define IDS_MFU_SRV64ADM_11             2107
#define IDS_MFU_SRV64ADM_12             2108
#define IDS_MFU_SRV64ADM_13             2109
#define IDS_MFU_SRV64ADM_14             2110
#define IDS_MFU_SRV64ADM_15             2111
#define IDM_MU_DISCONNECT               5000
#define IDM_MU_SECURITY                 5001
#define IDSYSPOPUP_LAST                 0x7fef
#define IDSYSPOPUP_OPENCOMMON           0x7ff0
#define IDSYSPOPUP_EXPLORECOMMON        0x7ff1
#define IDSYSPOPUP_STARTMENUPROP        0x7ff2

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
